name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Site
        env:
          BASE_PATH: '/'
        run: |
          npm run build
          touch build/.nojekyll

      - name: Debug: List Build Files
        run: ls -la build  # Debugging step to confirm build output

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Ensure this matches the download step
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Debug: List Available Artifacts
        run: ls -la

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages  # Ensure this matches the uploaded artifact
          path: build/

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
